#see https://developers.google.com/appengine/docs/java/configyaml/appconfig_yaml
#see https://developers.google.com/appengine/docs/python/config/appconfig
#
application: gcdc2013-vdrones
version: 0-17-0
runtime: go
api_version: go1
threadsafe: true
default_expiration: "5d"

handlers:
- url: /api/.*
  script: _go_app
- url: /
  static_files: web/index.html
  upload: web/index.html
- url: /(.*)
  static_files: web/\1
  upload: web/(.*)
