name: vdrones
version: 0.8.0
author: david bernard
description: An arcade game
homepage: https://vdrones.appspot.com/
documentation: https://github.com/davidB/vdrones
dependencies:
  asset_pack:
#    path: ../asset_pack
    git:
      ref: exp_progressbar
      url: git://github.com/davidB/asset_pack.git
  lawndart:
    path: ../lawndart
#  box2d: 0.0.7
  box2d:
    path: ../dartbox2d
  js: any
  browser: any
  logging: any
  web_ui: any
  vector_math: '>=0.9.7'
  widget:
    git: git://github.com/kevmoo/widget.dart.git
  dartemis:
#    path: ../dartemis
#    git: git://github.com/davidB/dartemis.git
    git: git://github.com/denniskaselow/dartemis.git
  dartemis_addons:
#    path: ../dartemis_addons
    git: git://github.com/davidB/dartemis_addons.git
dev_dependencies:
  unittest: any

#  three:
#    path: /home/dwayne/dart/three.dart
#  logging: 0.3.7+6
#  lawndart: 0.4.1
