name: vdrones
version: 0.12.0
author: david bernard
description: An arcade game
homepage: https://vdrones.appspot.com/
documentation: https://github.com/davidB/vdrones
dependencies:
  asset_pack: any
#    git: https://github.com/johnmccutchan/asset_pack.git
  box2d:
    git: https://github.com/dart-lang/dart-box2d.git
  browser: any
  dartemis: '>=0.4.1'
  dartemis_toolbox:
    path: ../dartemis_toolbox
  glf:
    path: ../glf
  js: any
  lawndart:
    git: https://github.com/davidB/lawndart.git
  logging: any
  simple_audio:
    git: https://github.com/johnmccutchan/simpleaudio.git
  vector_math: '>=1.3.0'
  web_ui: any
  widget:
    git: https://github.com/dart-lang/widget.dart
  game_loop:
    path: ../game_loop
#    git: https://github.com/johnmccutchan/game_loop.git
dev_dependencies:
  unittest: any

#    git:
#      ref: davidB
#      url: https://github.com/davidB/dartbox2d.git