name: vdrones
version: 0.16.1
author: david bernard
description: An arcade game
homepage: https://vdrones.appspot.com/
documentation: https://github.com/davidB/vdrones
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  asset_pack:
    git: https://github.com/johnmccutchan/asset_pack.git
  browser: any
  crypto: any
  dartemis: '>=0.4.1'
  dartemis_toolbox:
    #git: https://github.com/davidB/dartemis_toolbox.git
    path: ../dartemis_toolbox
  game_loop:
    git:
      ref: davidB
      url: https://github.com/davidB/game_loop.git
  glf:
    path: ../glf
#    git: https://github.com/davidB/glf.git
  google_games_v1_api: '>=0.4.1'
  google_oauth2_client: any
  google_plus_v1_api: '>=0.4.11'
  intl: any
  js: any
  lawndart: any
  logging: any
  protobuf:
    git: https://github.com/dart-lang/dart-protobuf.git
    version: '>=0.3.0'
  simple_audio:
    git:
      ref: davidB
      url: https://github.com/davidB/simpleaudio.git
  vector_math: '>=1.3.0'
  event_bus: '>=0.2.4'
  html_toolbox:
    path: ../html_toolbox
dev_dependencies:
  unittest: any
