name: vdrones
version: 0.6.1+1
author: david bernard
description: A sample web application
homepage: https://vdrones.appspot.com/
documentation: https://github.com/davidB/vdrones
dependencies:
  asset_pack: any
  lawndart: 
    path: ../lawndart
#  box2d: 0.0.7
  box2d:
    path: ../dartbox2d
  js: any
  browser: any
  logging: any
  web_ui: any
  vector_math: '>=0.9.7'
  widget:
    git: git://github.com/kevmoo/widget.dart.git
#    git:
#      ref: 0.2.4+p0
#      url: git://github.com/davidB/widget.dart.git
  dartemis: 
    path: ../dartemis
#    git: git://github.com/davidB/dartemis.git
  dartemis_addons: 
    path: ../dartemis_addons
#    git: git://github.com/davidB/dartemis_addons.git
dev_dependencies:
  unittest: any

#  three:
#    path: /home/dwayne/dart/three.dart
#  logging: 0.3.7+6
#  lawndart: 0.4.1
