#see https://developers.google.com/appengine/docs/java/configyaml/appconfig_yaml
#
application: vdrones
version: 0-5-0
runtime: java
#api_version: 1

#default_expiration: "30d"
welcome_files:
  - index.html

static_files:
  - include: /**.*
#  - exclude: /data/**.png

handlers:
